baseURL = "https://hux.ink/"
languageCode = "en-us"
timeZone = 'Asia/Shanghai'
title = "Counting StarsğŸ’«"
theme = "ivy"
disqusShortname = "è½è½vici"
hasCJKLanguage = true
enableEmoji = true
footnotereturnlinkcontents = "â†©"

[permalinks]
  posts = "/posts/:slug/"
  

[menu]
  [[menu.main]]
  name="å“”å“”"
  url="/bb/"
  weight="1"
  [[menu.main]]
  name="å½’æ¡£"
  url="/archives/"
  weight="2" 
  [[menu.main]]
  name="å…‰å½±"
  url="/album/"
  weight="3"
  [[menu.main]]
  name="èŠ±å›­"
  url="https://clip.hux.ink/"
  weight="4"
  [[menu.main]]
  name="æ‚¦åŠ¨"
  url="https://workout.hux.ink/"
  weight="5"
  [[menu.main]]
  name="å…³äº"
  url="/about/"
  weight="6"
 
  
  
  

  

[params]
  # description about this website
  description = "ğŸŒ©ï¸ğŸŒ©ï¸ğŸŒ©ï¸æ¬²ä¹°æ¡‚èŠ±åŒè½½é…’ï¼Œç»ˆä¸ä¼¼ï¼Œå°‘å¹´æ¸¸ã€‚"
  footer = "&copy; [Counting StarsğŸ’« | Since 2023](https://hux.ink/index.xml)"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"
  highlightjsVersion = "9.12.0"  

  

[params.twikoo]
	enable = true

[blackfriday]
extensionsmask = [ "noIntraEmphasis" ]
fractions = false

[markup.highlight]
codeFences = false

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser]
autoHeadingIDType = "blackfriday"

[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 1

[outputs]
  home = ["HTML","RSS","JSON"] # <domain>/atom.xml
  page = ["HTML"]
